const OVERPASS=["https://overpass-api.de/api/interpreter","https://overpass.kumi.systems/api/interpreter"];
const NOMINATIM="https://nominatim.openstreetmap.org/search";
const headers={"content-type":"application/json; charset=utf-8","cache-control":"public, max-age=120, s-maxage=300"};
const json=(statusCode,body)=>({statusCode,headers,body:JSON.stringify(body)});
async function overpass(query){let lastError;for(const endpoint of OVERPASS){try{const response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded","user-agent":"VargaTour/1.1 (indoor navigation)"},body:new URLSearchParams({data:query})});if(!response.ok)throw new Error(`Overpass ${response.status}`);return await response.json()}catch(error){lastError=error}}throw lastError||new Error("Overpass non disponibile")}
function centerOf(e){if(Number.isFinite(e.lat)&&Number.isFinite(e.lon))return{lat:e.lat,lng:e.lon};if(e.center&&Number.isFinite(e.center.lat)&&Number.isFinite(e.center.lon))return{lat:e.center.lat,lng:e.center.lon};if(Array.isArray(e.geometry)&&e.geometry.length){const pts=e.geometry.filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));if(pts.length){return{lat:pts.reduce((s,p)=>s+p.lat,0)/pts.length,lng:pts.reduce((s,p)=>s+p.lon,0)/pts.length}}}return null}
function venueType(t={}){if(t.aeroway==="aerodrome"||t.aeroway==="terminal")return"airport";if(t.railway==="station"||t.public_transport==="station")return"station";if(t.shop==="mall")return"mall";if(t.shop==="supermarket")return"supermarket";if(t.amenity==="hospital")return"hospital";if(t.amenity==="university")return"university";return"building"}
function venueLabel(t={}){return t.name||t["name:it"]||t.ref||({airport:"Aeroporto",station:"Stazione",mall:"Centro commerciale",supermarket:"Supermercato",hospital:"Ospedale",university:"Università"}[venueType(t)]||"Struttura")}
function pointCategory(t={}){if(t.aeroway==="gate")return"Gate";if(t.railway==="platform"||t.public_transport==="platform")return"Binario / piattaforma";if(t.amenity==="toilets")return"Bagni";if(t.amenity==="information"||t.information)return"Informazioni";if(t.amenity==="ticket_office"||t.shop==="ticket")return"Biglietteria";if(t.amenity==="luggage_locker"||t.amenity==="luggage_storage")return"Deposito bagagli";if(t.amenity==="car_rental")return"Autonoleggio";if(["cafe","restaurant","fast_food","food_court"].includes(t.amenity))return"Cibo e bevande";if(t.shop)return"Negozio";if(t.highway==="elevator"||t.indoor==="elevator")return"Ascensore";if(t.highway==="steps")return t.conveying?"Scala mobile":"Scale";if(t.door)return"Porta";if(t.entrance||t.railway==="train_station_entrance")return"Ingresso / uscita";if(t.checkin)return"Check-in";if(t.security)return"Controlli sicurezza";if(t.customs)return"Dogana";if(t.indoor==="room"||t.room)return"Locale";if(t.indoor==="corridor")return"Corridoio";return"Punto interno"}
function isUseful(t={}){return Boolean(t.name||t.ref||t.aeroway==="gate"||t.railway==="platform"||t.public_transport==="platform"||t.amenity||t.shop||t.entrance||t.door||t.railway==="train_station_entrance"||t.highway==="elevator"||t.highway==="steps"||t.indoor==="elevator"||t.checkin||t.security||t.customs||t.indoor==="room"||t.room)}
function unique(items){const seen=new Set();return items.filter(item=>{const key=`${item.name.toLowerCase()}|${item.category}|${item.level||""}|${item.lat.toFixed(5)}|${item.lng.toFixed(5)}`;if(seen.has(key))return false;seen.add(key);return true})}
function segmentKind(t={}){if(t.highway==="steps")return t.conveying?"escalator":"stairs";if(t.highway==="elevator"||t.indoor==="elevator")return"elevator";if(t.indoor==="corridor")return"corridor";if(t.highway==="footway"||t.highway==="pedestrian"||t.highway==="path")return"walkway";return"indoor"}
function isClosedGeometry(geometry){if(geometry.length<4)return false;const a=geometry[0],b=geometry[geometry.length-1];return Math.abs(a.lat-b.lat)<1e-8&&Math.abs(a.lng-b.lng)<1e-8}
function routeSegment(e){const geometry=Array.isArray(e.geometry)?e.geometry.filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)).map(p=>({lat:p.lat,lng:p.lon})):[];if(geometry.length<2)return null;const t=e.tags||{};const kind=segmentKind(t);const areaLike=t.area==="yes"||t.indoor==="room"||t.indoor==="area"||(t.indoor==="corridor"&&isClosedGeometry(geometry));if(areaLike&&kind!=="stairs"&&kind!=="elevator")return null;return{id:`osm-way-${e.id}`,level:t.level||t["level:ref"]||"",kind,coordinates:geometry}}
function sourceStats(points,routeSegments){const categories={};for(const p of points)categories[p.category]=(categories[p.category]||0)+1;const segments={};for(const s of routeSegments)segments[s.kind||"indoor"]=(segments[s.kind||"indoor"]||0)+1;return{categories,segments,totalPoints:points.length,totalSegments:routeSegments.length}}
export async function handler(event){try{const p=event.queryStringParameters||{};const action=p.action||"nearby";
if(action==="search"){const q=String(p.q||"").trim();if(q.length<2)return json(200,{items:[]});const url=new URL(NOMINATIM);url.search=new URLSearchParams({q:`${q}, Italia`,format:"jsonv2",countrycodes:"it",limit:"16",addressdetails:"1",extratags:"1"}).toString();const response=await fetch(url,{headers:{"user-agent":"VargaTour/1.1 (indoor navigation)"}});if(!response.ok)throw new Error("Ricerca struttura non disponibile");const data=await response.json();const items=data.filter(x=>/airport|aerodrome|aeroporto|station|stazione|railway|terminal|mall|shopping|supermarket|centro commerciale|ospedale|hospital|university|università/.test(`${x.type||""} ${x.category||""} ${x.display_name||""}`.toLowerCase())).map(x=>{const text=`${x.type} ${x.category} ${x.display_name}`.toLowerCase();let type="building";if(/airport|aerodrome|aeroporto/.test(text))type="airport";else if(/station|stazione|railway/.test(text))type="station";else if(/mall|shopping|centro commerciale/.test(text))type="mall";else if(/supermarket/.test(text))type="supermarket";else if(/hospital|ospedale/.test(text))type="hospital";else if(/university|università/.test(text))type="university";return{id:`nominatim-${x.osm_type}-${x.osm_id}`,name:String(x.display_name||"").split(",")[0],subtitle:x.display_name,type,lat:Number(x.lat),lng:Number(x.lon)}});return json(200,{items})}
const lat=Number(p.lat),lng=Number(p.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))return json(400,{error:"Coordinate non valide"});
if(action==="nearby"){const radius=Math.min(50000,Math.max(1000,Number(p.radius)||25000));const query=`[out:json][timeout:25];(nwr(around:${radius},${lat},${lng})[aeroway=aerodrome];nwr(around:${radius},${lat},${lng})[railway=station][station!=subway];nwr(around:${radius},${lat},${lng})[public_transport=station];nwr(around:${radius},${lat},${lng})[shop=mall];nwr(around:${radius},${lat},${lng})[shop=supermarket];nwr(around:${radius},${lat},${lng})[amenity=hospital];nwr(around:${radius},${lat},${lng})[amenity=university];);out center tags;`;const data=await overpass(query);const items=(data.elements||[]).map(e=>{const c=centerOf(e);if(!c)return null;return{id:`osm-${e.type}-${e.id}`,name:venueLabel(e.tags),subtitle:e.tags?.operator||e.tags?.brand||e.tags?.iata||"",type:venueType(e.tags),...c}}).filter(Boolean).slice(0,80);return json(200,{items})}
if(action==="indoor"){const radius=Math.min(2500,Math.max(200,Number(p.radius)||900));const query=`[out:json][timeout:35];(nwr(around:${radius},${lat},${lng})[indoor];nwr(around:${radius},${lat},${lng})[aeroway=gate];nwr(around:${radius},${lat},${lng})[railway=platform];nwr(around:${radius},${lat},${lng})[public_transport=platform];nwr(around:${radius},${lat},${lng})[railway=train_station_entrance];nwr(around:${radius},${lat},${lng})[entrance];nwr(around:${radius},${lat},${lng})[door];nwr(around:${radius},${lat},${lng})[highway=elevator];nwr(around:${radius},${lat},${lng})[indoor=elevator];nwr(around:${radius},${lat},${lng})[highway=steps];nwr(around:${radius},${lat},${lng})[amenity];nwr(around:${radius},${lat},${lng})[shop];way(around:${radius},${lat},${lng})[indoor=corridor];way(around:${radius},${lat},${lng})[highway=footway];way(around:${radius},${lat},${lng})[highway=pedestrian];way(around:${radius},${lat},${lng})[highway=path][indoor];way(around:${radius},${lat},${lng})[highway=steps];way(around:${radius},${lat},${lng})[highway=elevator];);out center geom tags;`;const data=await overpass(query);const elements=data.elements||[];const points=unique(elements.map(e=>{const c=centerOf(e),t=e.tags||{};if(!c||!isUseful(t))return null;const category=pointCategory(t);return{id:`osm-${e.type}-${e.id}`,name:t.name||t["name:it"]||t.ref||(category==="Gate"?`Gate ${t.ref||""}`.trim():category),category,level:t.level||t["level:ref"]||"",wheelchair:t.wheelchair||"",...c}}).filter(Boolean)).slice(0,700);const routeSegments=elements.filter(e=>e.type==="way").map(routeSegment).filter(Boolean).slice(0,1600);const levels=[...new Set([...points.map(x=>x.level),...routeSegments.map(x=>x.level)].filter(Boolean))].sort();const detailed=points.some(x=>x.level||["Gate","Binario / piattaforma","Ascensore","Scale","Scala mobile","Porta"].includes(x.category))||routeSegments.length>0;return json(200,{points,routeSegments,levels,detailed,source:"OpenStreetMap contributors",sourceStats:sourceStats(points,routeSegments),routingReady:routeSegments.some(s=>["corridor","walkway","stairs","escalator","elevator"].includes(s.kind))})}
return json(400,{error:"Azione non supportata"})}catch(error){return json(502,{error:error instanceof Error?error.message:"Servizio temporaneamente non disponibile"})}}
