"use client";
import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import Link from "next/link";
import { ArrowLeft,Compass,LocateFixed,MapPin,Navigation,Plane,Search,TrainFront,Accessibility,Building2,ShoppingCart } from "lucide-react";
import { IndoorMap } from "@/components/indoor-map";
type Hub={id:string;name:string;subtitle?:string;type:"airport"|"station"|"mall"|"supermarket"|"hospital"|"university"|"building";lat:number;lng:number};
type IndoorPoint={id:string;name:string;category:string;level?:string;wheelchair?:string;lat:number;lng:number};type Position={lat:number;lng:number;accuracy?:number};
function distanceMeters(a:Position,b:Position){const r=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lng-a.lng)*Math.PI/180,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*r*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
function bearing(a:Position,b:Position){const p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dl=(b.lng-a.lng)*Math.PI/180,y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(Math.atan2(y,x)*180/Math.PI+360)%360}
const typeName=(t:Hub["type"])=>({airport:"Aeroporto",station:"Stazione",mall:"Centro commerciale",supermarket:"Supermercato",hospital:"Ospedale",university:"Università",building:"Struttura"}[t]);
export default function IndoorGuidePage(){const[query,setQuery]=useState("");const[results,setResults]=useState<Hub[]>([]);const[nearby,setNearby]=useState<Hub[]>([]);const[hub,setHub]=useState<Hub|null>(null);const[points,setPoints]=useState<IndoorPoint[]>([]);const[destination,setDestination]=useState<IndoorPoint|null>(null);const[position,setPosition]=useState<Position|null>(null);const[loading,setLoading]=useState(false);const[message,setMessage]=useState("Scegli una struttura oppure usa la tua posizione.");const[detailed,setDetailed]=useState(false);const[category,setCategory]=useState("Tutti");const[level,setLevel]=useState("Tutti");const watchRef=useRef<number|null>(null);
useEffect(()=>()=>{if(watchRef.current!==null)navigator.geolocation?.clearWatch(watchRef.current)},[]);
async function searchHub(){const q=query.trim();if(q.length<2)return;setLoading(true);setMessage("Cerco la struttura…");try{const r=await fetch(`/.netlify/functions/indoor-guide?action=search&q=${encodeURIComponent(q)}`),d=await r.json();setResults(Array.isArray(d.items)?d.items:[]);setMessage(d.items?.length?"Scegli la struttura.":"Nessuna struttura trovata.")}catch{setMessage("Ricerca non disponibile.")}finally{setLoading(false)}}
function locate(){if(!navigator.geolocation){setMessage("GPS non disponibile.");return}setLoading(true);navigator.geolocation.getCurrentPosition(async p=>{const current={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};setPosition(current);try{const r=await fetch(`/.netlify/functions/indoor-guide?action=nearby&lat=${current.lat}&lng=${current.lng}&radius=30000`),d=await r.json(),items=Array.isArray(d.items)?d.items:[];items.sort((a:Hub,b:Hub)=>distanceMeters(current,a)-distanceMeters(current,b));setNearby(items);setMessage(items.length?"Ho trovato le strutture più vicine.":"Nessuna struttura trovata nelle vicinanze.")}catch{setMessage("Ricerca vicina non disponibile.")}finally{setLoading(false)}},()=>{setLoading(false);setMessage("Posizione non autorizzata.")},{enableHighAccuracy:true,timeout:12000,maximumAge:10000})}
async function openHub(item:Hub){setHub(item);setDestination(null);setPoints([]);setLoading(true);setMessage("Carico la mappa e i punti interni…");try{const r=await fetch(`/.netlify/functions/indoor-guide?action=indoor&lat=${item.lat}&lng=${item.lng}&radius=1200`),d=await r.json(),loaded=Array.isArray(d.points)?d.points:[];setPoints(loaded);setDetailed(Boolean(d.detailed));setMessage(loaded.length?`${loaded.length} punti sulla mappa. Tocca dove vuoi andare.`:"Mappa disponibile, ma i dettagli interni pubblici sono limitati.")}catch{setMessage("Non riesco a caricare i dettagli interni.")}finally{setLoading(false)}}
const startGuide=useCallback((point:IndoorPoint)=>{setDestination(point);setMessage(`Navigazione verso ${point.name}.`);if(!navigator.geolocation)return;if(watchRef.current!==null)navigator.geolocation.clearWatch(watchRef.current);watchRef.current=navigator.geolocation.watchPosition(p=>setPosition({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy}),()=>setMessage("Segnale GPS debole dentro la struttura."),{enableHighAccuracy:true,maximumAge:1500,timeout:12000})},[]);
const categories=useMemo(()=>["Tutti",...Array.from(new Set(points.map(p=>p.category))).sort()],[points]);const levels=useMemo(()=>["Tutti",...Array.from(new Set(points.map(p=>p.level).filter(Boolean) as string[])).sort()],[points]);const visible=useMemo(()=>points.filter(p=>(category==="Tutti"||p.category===category)&&(level==="Tutti"||p.level===level)),[points,category,level]);const nav=destination&&position?{distance:distanceMeters(position,destination),bearing:bearing(position,destination)}:null;
const icon=(item:Hub)=>item.type==="airport"?<Plane/>:item.type==="station"?<TrainFront/>:item.type==="supermarket"?<ShoppingCart/>:<Building2/>;
return <main className="indoor-page"><header className="indoor-topbar"><Link href="/" className="indoor-back"><ArrowLeft size={18}/> Varga Tour</Link><div><strong>Guida interna</strong><small>Mappe delle strutture</small></div></header>
<section className="indoor-hero"><div><p className="eyebrow"><Navigation size={16}/> Navigazione interna</p><h1>Una mappa per arrivare proprio lì.</h1><p>Aeroporti, stazioni, centri commerciali, supermercati, ospedali, università e altre grandi strutture mappate.</p></div><button className="indoor-locate" onClick={locate} disabled={loading}><LocateFixed/> Usa la mia posizione</button></section>
<section className="indoor-search-panel"><div className="indoor-search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void searchHub()} placeholder="Cerca aeroporto, stazione, centro commerciale, supermercato…"/><button onClick={()=>void searchHub()} disabled={loading}>Cerca</button></div><p className="indoor-status">{loading?"Caricamento…":message}</p></section>
{!hub&&(results.length>0||nearby.length>0)&&<section className="indoor-hub-grid">{(results.length?results:nearby).map(item=><button key={item.id} className="indoor-hub-card" onClick={()=>void openHub(item)}><span className="indoor-hub-icon">{icon(item)}</span><span><small>{typeName(item.type)}</small><strong>{item.name}</strong>{item.subtitle&&<em>{item.subtitle}</em>}</span><Navigation size={19}/></button>)}</section>}
{hub&&<section className="indoor-workspace"><div className="indoor-workspace-head"><div><small>{typeName(hub.type)}</small><h2>{hub.name}</h2><p>{detailed?"Dettagli interni disponibili sulla mappa.":"Mostro tutti i punti pubblici disponibili."}</p></div><button onClick={()=>{setHub(null);setDestination(null);setPoints([])}}>Cambia struttura</button></div>
<div className="indoor-map-wrap"><IndoorMap center={hub} points={visible} position={position} destination={destination} onSelect={startGuide}/><div className="indoor-map-legend"><span><b className="dot-user"/> Tu</span><span><b className="dot-dest"/> Destinazione</span><span>{points.length} punti</span></div></div>
{destination&&<div className="indoor-navigation-card"><div><Navigation size={54}/></div><div><small>Destinazione</small><h3>{destination.name}</h3><p>{destination.category}{destination.level?` · Piano ${destination.level}`:""}</p>{nav&&<strong className="indoor-distance">{nav.distance<1000?`${Math.round(nav.distance)} m`:`${(nav.distance/1000).toFixed(1)} km`}</strong>}</div><button onClick={()=>setDestination(null)}>Termina</button></div>}
{levels.length>1&&<div className="indoor-level-row"><strong>Piano</strong>{levels.map(x=><button key={x} className={level===x?"active":""} onClick={()=>setLevel(x)}>{x}</button>)}</div>}<div className="indoor-filter-row">{categories.slice(0,14).map(x=><button key={x} className={category===x?"active":""} onClick={()=>setCategory(x)}>{x}</button>)}</div>
<div className="indoor-point-list">{visible.map(point=><button key={point.id} onClick={()=>startGuide(point)}><span className="indoor-point-icon"><MapPin size={18}/></span><span><small>{point.category}{point.level?` · Piano ${point.level}`:""}</small><strong>{point.name}</strong>{point.wheelchair==="yes"&&<em><Accessibility size={13}/> Accessibile</em>}</span><Navigation size={18}/></button>)}</div>{points.length===0&&!loading&&<div className="indoor-empty"><Compass/><strong>Dettagli interni non disponibili</strong><p>La mappa della zona resta utilizzabile. I negozi, ingressi, corridoi, piani e servizi compaiono quando presenti nei dati OpenStreetMap.</p></div>}</section>}
<footer className="indoor-source">Mappa e dati: © OpenStreetMap contributors. Dentro gli edifici il GPS può essere meno preciso; Varga Tour mostra sempre l’accuratezza disponibile.</footer></main>}
